###
POST http://localhost:4004/odata/v4/approver/Capex(ID='aa79b405-add5-48c3-be3b-659e3fd36ab3',IsActiveEntity=true)/CapexApproverCatalogService.workflow
Content-Type: application/json

{
    "status": "Skipped",
    "childId": "ee3559a6-e9b0-42c2-8f34-b9a012fcc0a8",
    "comments": "2nd level"
}