###
POST http://localhost:4004/odata/v4/approver/Capex(ID='6f51c3a0-89f6-4ee6-b692-0d5aadba6083',IsActiveEntity=true)/CapexApproverCatalogService.workflow
Content-Type: application/json

{
    "status": "Approved",
    "childId": "f511c242-7821-4dd9-b376-23f326396b63",
    "comments": "2nd level"
}